name: "npm prepare"
description: "Prepare npm and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: volta-cli/action@main
    - name: Ignore .npmrc
      shell: bash
      run: git update-index --skip-worktree -- .npmrc
    - name: Configure Package Registry Authentication
      shell: bash
      run: |
        echo "//npm.pkg.github.com/:_authToken=${GITHUB_NPM_TOKEN}" >> .npmrc
    - name: Install modules
      shell: bash
      run: npm ci
