name: "npm prepare"
description: "Prepare npm and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: volta-cli/action@v4
    - name: Ignore .npmrc
      shell: bash
      run: git update-index --skip-worktree -- .npmrc
    - name: Configure Package Registry Authentication
      shell: bash
      run: |
        echo "//npm.pkg.github.com/:_authToken=${GITHUB_NPM_TOKEN}" >> .npmrc
    - name: Cache npm cache
      uses: actions/cache@v2
      env:
        cache-name: npm-cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ github.repository }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.repository }}-${{ env.cache-name }}-
          ${{ runner.os }}-${{ github.repository }}-
    - name: Install modules
      shell: bash
      run: npm ci
