name: "npm prepare"
description: "Prepare npm and install dependencies"
inputs:
   npm_token:
     description: "Private npm registry token."
     required: true
   test:
     description: "test."
     required: true

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - name: Test
      shell: bash
      run: echo ${{ inputs.test }}
    - name: Configure Package Registry Authentication
      shell: bash
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.npm_token }}" >> .npmrc
    - name: Install modules
      shell: bash
      run: npm ci
