name: "npm prepare"
description: "Prepare npm and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Configure Package Registry Authentication
      shell: bash
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_ACTIONS_PAT }}" > .npmrc
        echo "@parachutehome:registry=https://npm.pkg.github.com" >> .npmrc
    - name: Cache npm cache
      uses: actions/cache@v2
      env:
        cache-name: npm-cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ github.repository }}-test-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.repository }}-test-${{ env.cache-name }}-
          ${{ runner.os }}-${{ github.repository }}-test-
          ${{ runner.os }}-${{ github.repository }}-
    - name: Install modules
      shell: bash
      run: npm ci
