name: Shareable test and lint workflow

on:
  workflow_call:
    inputs:
      eslint:
        description: 'Should the `npm run lint:es` task be run?'
        required: false
        type: boolean
        default: true

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - name: Test
      shell: bash
      run: |
        pwd
        ls
    - name: Prepare npm
      uses: ./.github/actions/npm-prepare
    - name: Run tests
      run: npm test
  lint:
    if: inputs.eslint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - name: Prepare npm
      uses: ./.github/actions/npm-prepare
    - name: Run linting
      run: npm run lint:es
