name: Shareable test and lint workflow

on:
  workflow_call:
    inputs:
      github-registry:
        description: 'Adds private github npm registry if set.'
        required: false
        type: string

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - name: Prepare npm
      uses: ./.github/actions/prepare-npm
    - name: Run tests
      run: npm test
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - id: has-linting
      run: |
        HAS_ES_LINT=echo jq '.scripts."lint:es" != null'
        $HAS_ES_LINT >> $HAS_ES_LINT
    - name: Test
      run: echo $HAS_ES_LINT
    - name: Prepare npm
      uses: ./.github/actions/prepare-npm
    - name: Run linting
      if: ${{ steps.package_json }}
      run: npm run lint:es
