name: Shareable test and lint workflow

on:
  workflow_call:
    inputs:
      github-registry:
        description: 'Adds private github npm registry if set.'
        required: false
        type: string

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - name: Prepare npm
      uses: ./.github/actions/prepare-npm
    - name: Run tests
      run: npm test
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - name: Prepare npm
      uses: ./.github/actions/prepare-npm
    - id: has-linting
      run: |
        content=`jq 'if .scripts."lint:ess" != null then true else false end'`
    - name: Run linting
      if: ${{ steps.package_json }}
      run: npm run lint:es
