name: Shareable test and lint workflow

on:
  workflow_call:
    inputs:
      eslint:
        description: 'Should the `npm run lint:es` task be run?'
        required: false
        type: boolean
        default: true
    secrets:
      github_npm_token:
        description: 'Github npm registry token'
        required: false

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - name: Prepare npm
      uses: parachutehome/workflows/.github/actions/npm-prepare@trunk
      with:
        github_npm_token: ${{ inputs.github_npm_token }}
    - name: Run tests
      run: npm test
  lint:
    if: inputs.eslint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - name: Prepare npm
      uses: parachutehome/workflows/.github/actions/npm-prepare@trunk
      with:
        github_npm_token: ${{ secrets.github_npm_token }}
    - name: Run linting
      run: npm run lint:es
